language: python
cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10-dev

jobs:
  fast_finish: true

install:
  - travis_retry pip install tox-travis codecov
script:
  - tox -v

after_success:
  - codecov
