language: python
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
matrix:
  fast_finish: true
  include:
    - python: "3.9-dev"
    - python: "3.8"
      env: TOXENV=lint
    - python: "3.8"
    - python: "3.7"
    - python: "3.6"
    - python: "3.5"
    - python: "2.7"

install:
 - travis_retry pip install tox-travis

script:
 - tox

after_success:
  - |
    if [[ "$TOXENV" != "lint" ]]; then
      coverage report
      pip install -U codecov
      codecov
    fi

deploy:
  provider: pypi
  user: jazzband
  server: https://jazzband.co/projects/prettytable/upload
  distributions: sdist bdist_wheel
  password:
    secure: svV4fYtodwW+iTyFOm5ISEfhVwcA+6vTskD3x6peznc40TdMV9Ek8nT3Q/NB4lCbXoUw2qR4H6uhLCjesnv/VvVk/qbitCyD8ySlgwOV5n7NzJs8lC8EYaHSjGQjatTwJAokfGVYkPawkI7HXDqtDggLUQBK+Ag8HDW+XBSbQIU=
  on:
    tags: true
    repo: jazzband/prettytable
    python: 3.8
